project_name: grimd
dockers:
  - image_templates:
    - "ghcr.io/cottand/grimd:latest-amd64"
    - "ghcr.io/cottand/grimd:{{ .Tag }}-amd64"
    dockerfile: docker/alpine.gorelease.Dockerfile
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/cottand/grimd
      - --label=org.opencontainers.image.source=https://github.com/cottand/grimd
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    use: buildx
  - image_templates:
      - "ghcr.io/cottand/grimd:latest-arm64"
      - "ghcr.io/cottand/grimd:{{ .Tag }}-arm64"
    dockerfile: docker/gorelease.Dockerfile
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/cottand/grimd
      - --label=org.opencontainers.image.source=https://github.com/cottand/grimd
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    use: buildx
    goarch: arm64
docker_manifests:
  - name_template: 'ghcr.io/cottand/grimd:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/cottand/grimd:{{ .Tag }}-amd64'
      - 'ghcr.io/cottand/grimd:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/cottand/grimd:latest'
    image_templates:
      - 'ghcr.io/cottand/grimd:{{ .Tag }}-amd64'
      - 'ghcr.io/cottand/grimd:{{ .Tag }}-arm64'
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
