[book]
authors = ["Cottand"]
language = "en"
multilingual = false
src = "src"
title = "leng-doc"


[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/cottand/leng"
edit-url-template = "https://github.com/cottand/leng/edit/master/doc/{path}"