name: Test Nix Flake build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-24.05
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Enable KVM group perms (for NixOS tests)
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo apt-get update
        sudo apt-get install -y libvirt-clients libvirt-daemon-system libvirt-daemon virtinst bridge-utils qemu qemu-system-x86
        sudo usermod -a -G kvm,libvirt $USER

    - run: nix build . --show-trace

    - run: nix flake check
